name: auto build for artifact and auto deploy
on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '1.8' # The JDK version to make available on the path.

      - name: allow mvnw permission
        run: chmod +x ./mvnw
        working-directory: dashboard-spring/

      - name: backend dependency install
        run: ./mvnw install
        working-directory: dashboard-spring/

      - name: backend test
        run: ./mvnw test
        working-directory: dashboard-spring/

      - name: backend build
        run: ./mvnw test
        working-directory: dashboard-spring/

      - name: Archive backend build result
        uses: actions/upload-artifact@v2
        with:
          name: backend
          path: dashboard-spring/target/*.jar

      - name: remove existing files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: sh /root/ci-cd/auto-clean.sh

      - name: backend build file upload
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "dashboard-spring/target/*.jar"
          target: "/root/ci-cd"

      - name: run frontend and backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: sh /root/ci-cd/auto-run.sh